#!/usr/bin/env python3
"""Inventory every curated verse and flag the ones that may not stand alone.

The flags are hints for human review, not verdicts. They over-flag on purpose:
a wrong flag costs a line of reading, a missed fragment ships to every desktop.
"""
import argparse, json, re

# Surahs that are largely continuous narrative. A single ayah lifted out of one
# is far more likely to depend on what came before it.
NARRATIVE_SURAHS = {7, 11, 12, 18, 19, 20, 21, 26, 27, 28, 37, 38, 54, 71}

# A bare third-person subject with no antecedent inside the verse itself. An
# opening "And" or "So" is not a signal: Quranic translation uses them
# constantly on sentences that stand perfectly well alone.
BACKREF = re.compile(
    r"^(And |But |So |Then |Thus )?"
    r"(He|She|They|It|Them|Their|Those|These|Such|Therein|This|That)\b", re.I)

# Narrative dialogue. The imperative "Say," is an address to the reader and is
# self-contained; past-tense "said" is someone speaking inside a story.
REPORTED = re.compile(r"\bsaid\b|\bthey say\b|\bhe says\b", re.I)


def flags_for(v):
    out = []
    if v["surah"] in NARRATIVE_SURAHS and v["ayahStart"] > 10:
        out.append("narrative-surah")
    text = v["english"].strip()
    m = BACKREF.match(text)
    # A pronoun opening is harmless when the verse names its own subject right
    # after, as in "And Allah is Knowing" or "They who believe in the unseen".
    if m and not re.match(r"^\S+\s+(who|whom|which)\b", text[m.start(2):], re.I):
        head = text[:60]
        if not re.search(r"\b(Allah|Lord)\b", head):
            out.append("opens-with-backreference")
    if REPORTED.search(v["english"]):
        out.append("reported-speech")
    if v["ayahStart"] == v["ayahEnd"] and len(v["arabic"]) < 45:
        out.append("very-short")
    return out or ["none"]


def ref_of(v):
    r = f'{v["surah"]}:{v["ayahStart"]}'
    return r if v["ayahEnd"] == v["ayahStart"] else r + f'-{v["ayahEnd"]}'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", required=True)
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    verses = json.load(open(a.json))["verses"]
    rows, counts = [], {}
    for v in verses:
        f = flags_for(v)
        for x in f:
            counts[x] = counts.get(x, 0) + 1
        rows.append((ref_of(v), v, f))
    with open(a.out, "w") as fh:
        fh.write("# Verse audit\n\nGenerated by `Scripts/audit_verses.py`. ")
        fh.write("Flags are review hints, not verdicts.\n\n")
        fh.write("## Flag counts\n\n")
        for k in sorted(counts, key=lambda k: -counts[k]):
            fh.write(f"- `{k}`: {counts[k]}\n")
        fh.write("\n## Entries\n\n")
        fh.write("| Reference | Surah | Ar | En | Tier | Flags | English |\n")
        fh.write("|---|---|---|---|---|---|---|\n")
        for ref, v, f in rows:
            eng = v["english"].replace("|", "\\|")
            fh.write(f'| {ref} | {v["surahName"]} | {len(v["arabic"])} | '
                     f'{len(v["english"])} | {v["tier"]} | {",".join(f)} | {eng} |\n')
    flagged = sum(c for k, c in counts.items() if k != "none")
    print(f"wrote {a.out}: {len(rows)} entries, {flagged} flags")


if __name__ == "__main__":
    main()
